### ISSUE TITLE
Chromapper doesn't work on macOS 13

### ISSUE THREAD

**Issue by CodeCrafter07** [Caeden117/ChroMapper#433] opened 2022-10-25 21:17 UTC
**ChroMapper version**
1.11(1)

**Describe the Issue**
Opening chromapper causes it to crash. When opening it through terminal, it opened the updating screen, but crashed soon after.

**Provide Screenshots or Videos**
<img width="1112" alt="Screenshot 2022-10-25 at 5 13 23 PM" src="https://user-images.githubusercontent.com/104267012/197883103-c7857d64-9800-456c-87d2-8f6e0769b6a3.png">

**Steps to Reproduce**
Simply launching CML through terminal or finder

**Expected Behavior**
I expected it to launch, but it didn't

**Additional Context**
I am using a Mac with an M1 Pro. The crash may have something to do with the new OS update. It was working fine up until the point when I updated to macOS 13, and now I cannot get it to open.

**Comment by noah-friedman** [comment] 2023-01-21 21:33
Any update on this issue? Currently experiencing it on a MBP 2020 model with M1 chip.

**Comment by Caeden117** [comment] 2023-01-22 01:29
Unity 2021.1 seems to have issues running through Rosetta on Apple Silicon, which includes ChroMapper by extension. We currently only officially distribute Mac x64 builds (Intel based), so Rosetta is currently required to ChroMapper on Apple Silicon.

I am unsure if Unity 2021.1 includes support for building applications on native Apple Silicon, but if not, it could hopefully be resolved with a simple Unity upgrade. We would also need to add Apple Silicon distribution to the ChroMapper Launcher, which could take time.

**Comment by CodeCrafter07** [comment] 2023-01-22 01:48
I used the source code to build a new version with version 2021.3 and it launched without crashing

**Comment by noah-friedman** [comment] 2023-01-22 17:54
@CodeCrafter07 thanks for letting me know! I'm trying that now, also I'll see if I can build with 2021.1.15f1 natively for Silicon

**Comment by noah-friedman** [comment] 2023-01-22 19:06
Upon further investigation, it seems like I'm experiencing a _different_ error now. I'll open a separate issue.

Also, @Caeden117: theres a way to make a single "[Universal](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary)" app bundle to avoid any issues with Rosetta, and it's available in the Unity version currently used by the project.

<img width="742" alt="Screenshot 2023-01-22 at 1 59 47 PM" src="https://user-images.githubusercontent.com/44714422/213934775-89edc712-7219-4048-a9d6-f2b9869abe64.png">

I can confirm it builds and launches properly. This would fix the Rosetta issue without needing to modify the Launcher at all (assuming it doesn't break something else I'm not aware of). I'm happy to help with updating that!

**Comment by Caeden117** [comment] 2023-01-22 19:26
For continuous integration, it seems like [there is some code in an undocumented, macOS-specific assembly](https://forum.unity.com/threads/cannot-build-unity-2020-projects-using-command-line-on-macos-with-xcode-10-or-11.1084085/#post-7014124). Would you be willing to implement this in our [Build Script](https://github.com/Caeden117/ChroMapper/blob/master/Assets/Editor/SimpleEditorUtils.cs) and see if Unity will let you compile?

**Comment by noah-friedman** [comment] 2023-01-22 20:56
Yes, I will do that and let you know. In other news, I can run ChroMapper by downloading the Jenkins CI build/building from source, but CML still crashes with [this crash report](https://pastebin.com/mTtDk2Wa). Is there a repository for CML? (Looked but couldn't find it)

**Comment by Top-Cat** [comment] 2023-01-22 21:03
https://github.com/Top-Cat/CMLauncher

**Comment by Top-Cat** [comment] 2023-01-22 21:12
Guessing the native binary doesn't work on arm, good luck building xdelta3 for your platform it was pain

**Comment by noah-friedman** [comment] 2023-01-23 18:31
@Top-Cat built universal versions of xdelta3 and liblzma, but the issue persists (and I can confirm it is running an ARM64 binary). I had to configure xdelta3 not to include "xdelta3-main.h" and "xdelta3-test.h" because the former caused a symbol collision with the Xamarin framework and the latter depended on the former. When you built xdelta3-xdelta3.o did you do the same?

**Comment by noah-friedman** [comment] 2023-01-23 19:48
@Caeden117 confirmed Unity compiled the project successfully with those build options

**Closed** 2023-10-01 13:09 UTC
Labels: bug
